### ISSUE TITLE
Warn that FFTW.jl must be imported to use `FFTESSMethod`

### ISSUE THREAD

**Issue by sethaxen** [devmotion/InferenceDiagnostics.jl#13]
`ess_rhat` with `FFTESSMethod` requires methods of `AbstractFFTs.plan_fft!` and `AbstractFFTs.plan_ifft!` that are defined in FFTW.jl, so if the user doesn't call `using FFTW`, they get a very unhelpful message:

```julia
julia> x = randn(1000, 10, 4);

julia> ess_rhat(x; method=FFTESSMethod())
ERROR: MethodError: no method matching plan_fft!(::Matrix{ComplexF64}, ::Int64)
Closest candidates are:
  plan_fft!(::AbstractArray; kws...) at /Users/sethaxen/.julia/packages/AbstractFFTs/JebmH/src/definitions.jl:52
```
It would be better to give the user a more helpful message telling them to load `FFTW` first.

**Comment by devmotion** [comment]
They don't have to use FFTW (it's the main point that you can pick the FFT backend, e.g. you can also use https://github.com/JuliaApproximation/FastTransforms.jl). I agree though that it would be good to document it better.
